version: '3.9'

services:
  backend:
    build:
      context: ./backend
    container_name: patent-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: patent-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://patent-backend:8000
    volumes:
      - ./frontend:/app
    restart: always
